version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test:unit

  build-lib:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run build-library
      - store_artifacts:
        path: /dist
        destination: library-artifacts

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build-lib:
          requires:
            - test
