// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import AddToCartButton from "./AddToCartButton.vue";
import FlyoutCart from "./FlyoutCart.vue";
import FlyoutCartItem from "./FlyoutCartItem.vue";
import ProductPrice from "./ProductPrice.vue";
import Spinner from "./Spinner.vue";

export { AddToCartButton, FlyoutCart, FlyoutCartItem, ProductPrice, Spinner };

function install(Vue) {
  Vue.component("AddToCartButton", AddToCartButton);
  Vue.component("FlyoutCart", FlyoutCart);
  Vue.component("FlyoutCartItem", FlyoutCartItem);
  Vue.component("ProductPrice", ProductPrice);
  Vue.component("Spinner", Spinner);
}

export default { install: install };
