// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import AddToCartButton from './AddToCartButton.vue'
import FlyoutCart from './FlyoutCart.vue'
import FlyoutCartItem from './FlyoutCartItem.vue'
import ProductPrice from './ProductPrice.vue'
import Spinner from './Spinner.vue'

// Export components individually
export { AddToCartButton, FlyoutCart, FlyoutCartItem, ProductPrice, Spinner }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('AddToCartButton', AddToCartButton)
  Vue.component('FlyoutCart', FlyoutCart)
  Vue.component('FlyoutCartItem', FlyoutCartItem)
  Vue.component('ProductPrice', ProductPrice)
  Vue.component('Spinner', Spinner)
}

// Export the library as a plugin
export default { install: install }
