// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import AddToCartButton from './AddToCartButton.vue'
import ProductPrice from './ProductPrice.vue'
import Spinner from './Spinner.vue'

export { AddToCartButton, ProductPrice, Spinner }

function install(Vue) {
  Vue.component('AddToCartButton', AddToCartButton)
  Vue.component('ProductPrice', ProductPrice)
  Vue.component('Spinner', Spinner)
}

export default { install: install }
